name: Build ROS2 for iOS
on:
  workflow_dispatch:
  workflow_call:
jobs:
  build-ros2-base:
    runs-on: macos-latest
    timeout-minutes: 1200
    strategy:
      matrix:
        platformArch: [iOS, iOS_Simulator, iOS_Simulator_M1, macCatalyst, macCatalyst_M1]
    steps:
      - uses: actions/checkout@v3

      - name: Setup cmake
        uses: jwlawson/actions-setup-cmake@v1.12
        with:
          cmake-version: '3.23.x'

      - name: Fetch cached Python environment
        run: source ci_helper.sh ${{ matrix.platformArch }} && fetchCachedPythonEnvAndPrebuiltDeps && extractArtifacts

      - name: Build ROS2
        id: build_ros2
        run: source ros2PythonEnv/bin/activate && source build_ros2.sh ${{ matrix.platformArch }} && buildRos2Base

      - name: Archive ROS2 and dependencies
        run: tar cJf ros2_${{ matrix.platformArch }}.tar.xz ros2_${{ matrix.platformArch }}/

      - name: Publish ROS2 for release
        uses: actions/upload-artifact@v3
        with:
          name: ros2_${{ matrix.platformArch }}
          path: ros2_${{ matrix.platformArch }}.tar.xz
