name: Build dependencies
on:
  workflow_dispatch:
  workflow_call:
jobs:
  cache-python-environment:
    runs-on: macos-latest
    if: ${{ false }}
    steps:
      - uses: actions/checkout@v3

      - name: Create Python virtual environment and install packages
        run: python3 -m venv ros2PythonEnv

      - name: Install pip packages
        run: source ros2PythonEnv/bin/activate && python3 -m pip install -r requirements.txt

      - name: Archive the environment
        run: tar cJf python_venv.tar.xz ros2PythonEnv/

      - uses: actions/upload-artifact@v3
        with:
          name: python_venv
          path: python_venv.tar.xz

  build-dependencies:
    runs-on: macos-latest
    timeout-minutes: 1200
    strategy:
      matrix:
        platformArch: [macOS] # iOS, iOS_Simulator, iOS_Simulator_M1, macCatalyst, macCatalyst_M1
    steps:
      - uses: actions/checkout@v3

      - name: Setup cmake
        uses: jwlawson/actions-setup-cmake@v1.12
        with:
          cmake-version: '3.23.x'

      - name: Install X11 (XQuartz)
        run: brew install xquartz

      - name: Build dependencies
        run: ./build_deps.sh ${{ matrix.platformArch }}

      - name: Package dependencies
        run: tar cJf deps_${{ matrix.platformArch }}.tar.xz ros2_${{ matrix.platformArch }}/deps/

      - uses: actions/upload-artifact@v3
        with:
          name: deps_${{ matrix.platformArch }}
          path: deps_${{ matrix.platformArch }}.tar.xz
