name: Build dependencies
on:
  workflow_dispatch:
  workflow_call:
  push:
    branches:
      deps-ci
jobs:
  build-core:
    uses: ./.github/workflows/subdeps.yaml
    with:
      collection: core

  build-boostrvizmoveit:
    needs: build-core
    uses: ./.github/workflows/subdeps.yaml
    with:
      collection: boostrvizmoveit

  build-opencv:
    needs: build-core
    uses: ./.github/workflows/subdeps.yaml
    with:
      collection: opencv

  build-qt5:
    needs: build-core
    uses: ./.github/workflows/subdeps.yaml
    with:
      collection: qt5

  combine:
    needs: [build-core, build-boostrvizmoveit, build-opencv, build-qt5]
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
      - run: ./extract_artifacts.sh
      - run: tar cJf deps_macOS.tar.xz ros2_macOS/deps/
      - uses: actions/upload-artifact@v3
        with:
          name: deps_macOS
          path: deps_macOS.tar.xz
