name: Build everything for release
on:
  push:
    tags:
      - '**'
jobs:
  #build-deps:
  #  uses: ./.github/workflows/deps.yaml

  build-ros2-base:
    uses: ./.github/workflows/base.yaml

  build-rviz2:
    uses: ./.github/workflows/rviz2.yaml
    needs: build-ros2-base #, build-deps

  build-moveit2:
    uses: ./.github/workflows/moveit2.yaml
    needs: build-rviz2

  build-tutorials:
    uses: ./.github/workflows/tutorials.yaml
    needs: build-moveit2
